# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - name: Build Library Install
        run: npm install
        
      - name: React Build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/myapp-frontend:${{ github.sha }}
          platforms: |
            linux/amd64
            linux/arm64

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Git Config
        run: |
          git config --global user.name ${{ github.repository_owner }}
          git config --global user.email "gywhd408@naver.com"

      - name: Clone Deploy Repository
        run: |
          git clone --depth 1 --branch main https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository_owner }}/argocd-deploy.git

      - name: Update image tage
        run: |
          cd argocd-deploy
          sed -i "s|ghcr.io/${{ github.repository_owner }}/myapp-frontend:.*|ghcr.io/${{ github.repository_owner }}/myapp-frontend:${{ github.sha }}|" ./front/deployment.yaml

          git add .
          git commit -m "Update deploy image tag to ${{ github.sha }}"
          git push origin main